version: "3.7"
services:
  frontend_app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: muni-app-front
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "80:80"
    environment:
      - HOST=0.0.0.0
    restart: unless-stopped
